### ISSUE TITLE
Traverse Biomes Spawning In Random Places/The Wrong Dimension

### ISSUE THREAD

**Issue by KKotik** [MysticMods/Traverse#27]
### General Information

**Describe the bug:**
My end looking like this: 
![image](https://user-images.githubusercontent.com/45950781/101457104-181d4f00-3946-11eb-991c-de18ebf198e4.png)

**Versions:**
- Forge: 35.1.0.10
- Minecraft: 1.16.4
- Mod: 1.16.4-0.4.2.3

**Comment by noobanidus** [comment]
Hi there!

Unfortunately I didn't get any notification of this, sorry. I'll be looking into it presently.

**Comment by noobanidus** [comment]
So, I'm not able to replicate this is a development environment. It's possible this has to do with biome shuffling:

- Is this a pre-existing world that you added traverse to?
- Are you running any other mods that effect end biome generation whereby biome shuffling could be causing traverse biomes to be shuffled in?

**Comment by noobanidus** [comment]
Can you try [this build](https://cdn.discordapp.com/attachments/605201246248501288/787486393663750164/traverse-1.16.4-0.4.2.3-test.jar) for me? Someone identified a potential issue that could be causing it. 

If that doesn't fix it, it might be something to do with the biome shuffling, which I thought had been fixed.

**Comment by noobanidus** [comment]
@KKotik Were you able to try that build? Or were you able to give me a list of other biomes, as I was unable to reproduce it in a dev environment.

**Comment by noobanidus** [comment]
I'm still unable to confirm this and haven't had any other reports. I'll leave this issue open so people can comment on it if there are problems in the future. I'm hopeful that the core issue here has been resolved though.

**Comment by fusionbolt18** [comment]
@noobanidus Hey so my friend is having the same problem on his server so we're gonna test out that build for you and see what happens

**Comment by fusionbolt18** [comment]
ok so we tested that build out and it is still happening. We've got traverse biomes all over the end.

**Comment by fusionbolt18** [comment]
> So, I'm not able to replicate this is a development environment. It's possible this has to do with biome shuffling:
> 
> * Is this a pre-existing world that you added traverse to?
> * Are you running any other mods that effect end biome generation whereby biome shuffling could be causing traverse biomes to be shuffled in?

FYI: We always had traverse in our world, but the two End mods that add biomes we have are Endergetic Expansion and Outer End.

**Comment by fusionbolt18** [comment]
A few more things after a bit more testing. We tried with only endergetic and it happened. We tried with only outer end and it happened. We tried with none and it did not happen. 

Another thing is that this only seems to happen on servers and not singleplayer.

**Comment by noobanidus** [comment]
Can you try installing [Chocolate Fix](https://www.curseforge.com/minecraft/mc-mods/chocolate-fix) and then testing with a *new world* (specifically) or a world that wasn't corrupted? At least I have reproduction steps now though, I think.

**Comment by noobanidus** [comment]
@fusionbolt18 After having re-read your post I realised that this is most likely you have an older version of Traverse.

I'm not able to replicate it with the latest version from CurseForge & Endergetic Biome:

![](https://i.imgur.com/oLtw8ff.png)

If you could drop your Traverse version somewhere or try out an updated version and get back to me, that would be great.

**Comment by noobanidus** [comment]
So, this more directly appears to be some sort of biome data corruption, as this happened on a multiplayer server I was maintaining.

When each biome is registered, it's given a numerical key by Forge. That key is then what is used for actual world generation.

For whatever reason, the biome key that **is registered as spawning in the end** doesn't end up actually being the correct key for that biome, but instead ends up being the key for another biome.

**Hacky solution**: this requires that you stop your server and perform the following steps:

- Delete the End dimension folder (making a back-up if you need)
- Download your level.dat file (making a back-up)
- Using [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases), open the level.dat.
- Find the section on the dragon fight and remove that (otherwise it may cause issues with mobs; this may potentially result in duplication of the dragon egg on your server, but it's a workable option)
- Find the "fml" section and look for the registries, and from there look for the biomes.
- Determine what biome it is that you **expected** would appear in the end and note down that number. (In the case of just Endergetic it was as simple as finding the Poise Forest ID, for other mods this may be more difficult as there may be more biome corruption). *Note: this will require you to go through expanding a number of nodes to find it, and nodes are not in numerical order.*
- Determine what biome it is that is **actually** spawning in the end and note down that number.
- I then wrote the numbers out on a piece of paper -- the number -- the current biome it was linked to according to the registry -- and then the biome that I believe it should be linked to.
- I then crossed out the "current" biome.
- Finally, I found the first biome that the number *should* be linked to and double-clicked on it to change the value. Then I repeated this process with the second biome.
- I then saved the level.dat file and re-uploaded it to the server.

It is unfortunately a tedious process but one that can work "in place".

I'm uncertain if this still occurs if the world is created using 1.16.5 versions of Forge, although in my instance the world was definitely created on 1.16.4.
